### PR TITLE
added fix for image clipping; added support for default background color

### PR DESCRIPTION
**Pull request by karlmonson**

### CODE REVIEW

**Comment by karlmonson** [comment]
New $_GET parameters available: &top= and &left= for dynamically setting the clipping starting point. Also set the default background color to white for screenshots where no background color is defined. I am working on adding this as an available $_GET parameter, will submit another pull request when it is stable.

**Comment by karlmonson** [comment]
added $_GET parameter &bg= for dynamic background colors if webpage has no background color specified.

**Comment by karlmonson** [comment]
added $_GET parameter &format= with available options jpg or png. Selecting png supports image transparency.

**Comment by MASNathan** [comment]
Hello @karlmonson 

Thanks for your submission.

As I migrated the script to OOP I used some of your ideas, like clipping the image and setting the background to white.

Although some funcinalities were migrated, others are missing like image type selection, and dynamic background color. 

If you have some spare time please fell free to update your code and proceed with the changes.

**Pull request closed without merging**
